### ISSUE TITLE
[53h] Implement API for new comments logic

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.backend#5]
Implement GraphQL API for comments smart display and pagination based on the parent feed. UOSnetwork/ucom.frontend#26
- [x] [24h] GraphQL implementation
- [x] [6h] user profile feed
- [x] [4h] user newsfeed
- [x] [4h] community profile feed
- [x] [5h] single post query
- [x] [6h] tag profile feed
- [ ]  posts overview feed #13 
- [x] [4h] REST API backward compatibility
